const columns = [
  { name: "NOMBRE", uid: "name", sortable: true },
  { name: "ROL", uid: "rol", sortable: true },
  { name: "EVENTO", uid: "event" },
  { name: "ESTADO", uid: "status", sortable: true },
  { name: "ACCIONES", uid: "actions" },
];

const statusOptions = [
  { name: "Aceptado", uid: "aceptado" },
  { name: "Pendiente", uid: "pendiente" },
  { name: "Rechazado", uid: "rechazado" },
];
const users = [
  {
    id: 1,
    name: "Tony Reichert",
    rol: "Director Ejecutivo (CEO)",
    event: "Conferencia de Innovación 2024",
    status: "aceptado",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "tony.reichert@example.com",
  },
  {
    id: 2,
    name: "Zoey Lang",
    rol: "Líder Técnico",
    event: "Hackathon de Desarrollo",
    status: "pendiente",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026704d",
    email: "zoey.lang@example.com",
  },
  {
    id: 3,
    name: "Jane Fisher",
    rol: "Desarrollador Senior",
    event: "Taller de Seguridad Informática",
    status: "aceptado",
    avatar: "https://i.pravatar.cc/150?u=a04258114e29026702d",
    email: "jane.fisher@example.com",
  },
  {
    id: 4,
    name: "William Howard",
    rol: "Gerente de Comunicaciones (C.M.)",
    event: "Reunión Anual de Marketing",
    status: "rechazado",
    avatar: "https://i.pravatar.cc/150?u=a048581f4e29026701d",
    email: "william.howard@example.com",
  },
  {
    id: 5,
    name: "Kristen Copper",
    rol: "Gerente Senior",
    event: "Seminario de Liderazgo",
    status: "aceptado",
    avatar: "https://i.pravatar.cc/150?u=a092581d4ef9026700d",
    email: "kristen.cooper@example.com",
  },
  {
    id: 6,
    name: "Brian Kim",
    rol: "Gerente de Producto",
    event: "Foro de Gestión de Proyectos",
    status: "aceptado",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29026024d",
    email: "brian.kim@example.com",
  },
  {
    id: 7,
    name: "Michael Hunt",
    rol: "Diseñador",
    event: "Concurso de Diseño Creativo",
    status: "pendiente",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e29027007d",
    email: "michael.hunt@example.com",
  },
  {
    id: 8,
    name: "Samantha Brooks",
    rol: "Gerente de Recursos Humanos",
    event: "Cumbre de Recursos Humanos",
    status: "aceptado",
    avatar: "https://i.pravatar.cc/150?u=a042581f4e27027008d",
    email: "samantha.brooks@example.com",
  },
  {
    id: 9,
    name: "Frank Harrison",
    rol: "Gerente Financiero",
    event: "Conferencia de Finanzas 2024",
    status: "rechazado",
    avatar: "https://i.pravatar.cc/150?img=4",
    email: "frank.harrison@example.com",
  },
  {
    id: 10,
    name: "Emma Adams",
    rol: "Gerente de Operaciones",
    event: "Taller de Operaciones",
    status: "aceptado",
    avatar: "https://i.pravatar.cc/150?img=5",
    email: "emma.adams@example.com",
  },
  {
    id: 11,
    name: "Brandon Stevens",
    rol: "Desarrollador Junior",
    event: "Bootcamp de Programación",
    status: "aceptado",
    avatar: "https://i.pravatar.cc/150?img=8",
    email: "brandon.stevens@example.com",
  },
  {
    id: 12,
    name: "Megan Richards",
    rol: "Gerente de Producto",
    event: "Workshop de Metodologías Ágiles",
    status: "pendiente",
    avatar: "https://i.pravatar.cc/150?img=10",
    email: "megan.richards@example.com",
  },
  {
    id: 13,
    name: "Oliver Scott",
    rol: "Gerente Senior",
    event: "Seminario de Estrategias de Ventas",
    status: "aceptado",
    avatar: "https://i.pravatar.cc/150?img=12",
    email: "oliver.scott@example.com",
  },
];

export { columns, users, statusOptions };
